/*
 * FINBOURNE Insights API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Insights.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Insights.Sdk.Model
{
    /// <summary>
    /// Identity population and activity counts for the domain, pivoted from the latest tranche the identity metrics provider collected.
    /// </summary>
    [DataContract(Name = "IdentityMetricsDataSet")]
    public partial class IdentityMetricsDataSet : IEquatable<IdentityMetricsDataSet>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IdentityMetricsDataSet" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected IdentityMetricsDataSet() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="IdentityMetricsDataSet" /> class.
        /// </summary>
        /// <param name="name">The name of this data set. Always &#x60;IdentityMetrics&#x60;, matching the corresponding Finbourne.Insights.WebApi.Dtos.Metrics.MetricDataSet value and Finbourne.Insights.WebApi.Dtos.Metrics.MetricsResponse property. (required).</param>
        /// <param name="collectedAt">The timestamp of the tranche these values were collected in, in UTC, or null if no tranche was returned..</param>
        /// <param name="personalUsers">The number of personal (human) users in the domain, or null if not reported..</param>
        /// <param name="serviceUsers">The number of service users in the domain, or null if not reported..</param>
        /// <param name="neverLoggedIn">The number of users that have never logged in, or null if not reported..</param>
        /// <param name="ignored">The number of users excluded from the other counts, or null if not reported..</param>
        /// <param name="accountLocked">The number of users whose account is locked, or null if not reported..</param>
        /// <param name="suspendedPwReset">The number of users suspended pending a password reset, or null if not reported..</param>
        /// <param name="createdLast24Hours">The number of users created in the last 24 hours, or null if not reported..</param>
        /// <param name="createdLast7Days">The number of users created in the last 7 days, or null if not reported..</param>
        /// <param name="createdLast30Days">The number of users created in the last 30 days, or null if not reported..</param>
        /// <param name="activeLast24Hours">The number of users active in the last 24 hours, or null if not reported..</param>
        /// <param name="activeLast7Days">The number of users active in the last 7 days, or null if not reported..</param>
        /// <param name="activeLast30Days">The number of users active in the last 30 days, or null if not reported..</param>
        public IdentityMetricsDataSet(string name = default(string), DateTimeOffset? collectedAt = default(DateTimeOffset?), long? personalUsers = default(long?), long? serviceUsers = default(long?), long? neverLoggedIn = default(long?), long? ignored = default(long?), long? accountLocked = default(long?), long? suspendedPwReset = default(long?), long? createdLast24Hours = default(long?), long? createdLast7Days = default(long?), long? createdLast30Days = default(long?), long? activeLast24Hours = default(long?), long? activeLast7Days = default(long?), long? activeLast30Days = default(long?))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for IdentityMetricsDataSet and cannot be null");
            }
            this.Name = name;
            this.CollectedAt = collectedAt;
            this.PersonalUsers = personalUsers;
            this.ServiceUsers = serviceUsers;
            this.NeverLoggedIn = neverLoggedIn;
            this.Ignored = ignored;
            this.AccountLocked = accountLocked;
            this.SuspendedPwReset = suspendedPwReset;
            this.CreatedLast24Hours = createdLast24Hours;
            this.CreatedLast7Days = createdLast7Days;
            this.CreatedLast30Days = createdLast30Days;
            this.ActiveLast24Hours = activeLast24Hours;
            this.ActiveLast7Days = activeLast7Days;
            this.ActiveLast30Days = activeLast30Days;
        }

        /// <summary>
        /// The name of this data set. Always &#x60;IdentityMetrics&#x60;, matching the corresponding Finbourne.Insights.WebApi.Dtos.Metrics.MetricDataSet value and Finbourne.Insights.WebApi.Dtos.Metrics.MetricsResponse property.
        /// </summary>
        /// <value>The name of this data set. Always &#x60;IdentityMetrics&#x60;, matching the corresponding Finbourne.Insights.WebApi.Dtos.Metrics.MetricDataSet value and Finbourne.Insights.WebApi.Dtos.Metrics.MetricsResponse property.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The timestamp of the tranche these values were collected in, in UTC, or null if no tranche was returned.
        /// </summary>
        /// <value>The timestamp of the tranche these values were collected in, in UTC, or null if no tranche was returned.</value>
        [DataMember(Name = "collectedAt", EmitDefaultValue = true)]
        public DateTimeOffset? CollectedAt { get; set; }

        /// <summary>
        /// The number of personal (human) users in the domain, or null if not reported.
        /// </summary>
        /// <value>The number of personal (human) users in the domain, or null if not reported.</value>
        [DataMember(Name = "personalUsers", EmitDefaultValue = true)]
        public long? PersonalUsers { get; set; }

        /// <summary>
        /// The number of service users in the domain, or null if not reported.
        /// </summary>
        /// <value>The number of service users in the domain, or null if not reported.</value>
        [DataMember(Name = "serviceUsers", EmitDefaultValue = true)]
        public long? ServiceUsers { get; set; }

        /// <summary>
        /// The number of users that have never logged in, or null if not reported.
        /// </summary>
        /// <value>The number of users that have never logged in, or null if not reported.</value>
        [DataMember(Name = "neverLoggedIn", EmitDefaultValue = true)]
        public long? NeverLoggedIn { get; set; }

        /// <summary>
        /// The number of users excluded from the other counts, or null if not reported.
        /// </summary>
        /// <value>The number of users excluded from the other counts, or null if not reported.</value>
        [DataMember(Name = "ignored", EmitDefaultValue = true)]
        public long? Ignored { get; set; }

        /// <summary>
        /// The number of users whose account is locked, or null if not reported.
        /// </summary>
        /// <value>The number of users whose account is locked, or null if not reported.</value>
        [DataMember(Name = "accountLocked", EmitDefaultValue = true)]
        public long? AccountLocked { get; set; }

        /// <summary>
        /// The number of users suspended pending a password reset, or null if not reported.
        /// </summary>
        /// <value>The number of users suspended pending a password reset, or null if not reported.</value>
        [DataMember(Name = "suspendedPwReset", EmitDefaultValue = true)]
        public long? SuspendedPwReset { get; set; }

        /// <summary>
        /// The number of users created in the last 24 hours, or null if not reported.
        /// </summary>
        /// <value>The number of users created in the last 24 hours, or null if not reported.</value>
        [DataMember(Name = "createdLast24Hours", EmitDefaultValue = true)]
        public long? CreatedLast24Hours { get; set; }

        /// <summary>
        /// The number of users created in the last 7 days, or null if not reported.
        /// </summary>
        /// <value>The number of users created in the last 7 days, or null if not reported.</value>
        [DataMember(Name = "createdLast7Days", EmitDefaultValue = true)]
        public long? CreatedLast7Days { get; set; }

        /// <summary>
        /// The number of users created in the last 30 days, or null if not reported.
        /// </summary>
        /// <value>The number of users created in the last 30 days, or null if not reported.</value>
        [DataMember(Name = "createdLast30Days", EmitDefaultValue = true)]
        public long? CreatedLast30Days { get; set; }

        /// <summary>
        /// The number of users active in the last 24 hours, or null if not reported.
        /// </summary>
        /// <value>The number of users active in the last 24 hours, or null if not reported.</value>
        [DataMember(Name = "activeLast24Hours", EmitDefaultValue = true)]
        public long? ActiveLast24Hours { get; set; }

        /// <summary>
        /// The number of users active in the last 7 days, or null if not reported.
        /// </summary>
        /// <value>The number of users active in the last 7 days, or null if not reported.</value>
        [DataMember(Name = "activeLast7Days", EmitDefaultValue = true)]
        public long? ActiveLast7Days { get; set; }

        /// <summary>
        /// The number of users active in the last 30 days, or null if not reported.
        /// </summary>
        /// <value>The number of users active in the last 30 days, or null if not reported.</value>
        [DataMember(Name = "activeLast30Days", EmitDefaultValue = true)]
        public long? ActiveLast30Days { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IdentityMetricsDataSet {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  CollectedAt: ").Append(CollectedAt).Append("\n");
            sb.Append("  PersonalUsers: ").Append(PersonalUsers).Append("\n");
            sb.Append("  ServiceUsers: ").Append(ServiceUsers).Append("\n");
            sb.Append("  NeverLoggedIn: ").Append(NeverLoggedIn).Append("\n");
            sb.Append("  Ignored: ").Append(Ignored).Append("\n");
            sb.Append("  AccountLocked: ").Append(AccountLocked).Append("\n");
            sb.Append("  SuspendedPwReset: ").Append(SuspendedPwReset).Append("\n");
            sb.Append("  CreatedLast24Hours: ").Append(CreatedLast24Hours).Append("\n");
            sb.Append("  CreatedLast7Days: ").Append(CreatedLast7Days).Append("\n");
            sb.Append("  CreatedLast30Days: ").Append(CreatedLast30Days).Append("\n");
            sb.Append("  ActiveLast24Hours: ").Append(ActiveLast24Hours).Append("\n");
            sb.Append("  ActiveLast7Days: ").Append(ActiveLast7Days).Append("\n");
            sb.Append("  ActiveLast30Days: ").Append(ActiveLast30Days).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as IdentityMetricsDataSet);
        }

        /// <summary>
        /// Returns true if IdentityMetricsDataSet instances are equal
        /// </summary>
        /// <param name="input">Instance of IdentityMetricsDataSet to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(IdentityMetricsDataSet input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.CollectedAt == input.CollectedAt ||
                    (this.CollectedAt != null &&
                    this.CollectedAt.Equals(input.CollectedAt))
                ) && 
                (
                    this.PersonalUsers == input.PersonalUsers ||
                    (this.PersonalUsers != null &&
                    this.PersonalUsers.Equals(input.PersonalUsers))
                ) && 
                (
                    this.ServiceUsers == input.ServiceUsers ||
                    (this.ServiceUsers != null &&
                    this.ServiceUsers.Equals(input.ServiceUsers))
                ) && 
                (
                    this.NeverLoggedIn == input.NeverLoggedIn ||
                    (this.NeverLoggedIn != null &&
                    this.NeverLoggedIn.Equals(input.NeverLoggedIn))
                ) && 
                (
                    this.Ignored == input.Ignored ||
                    (this.Ignored != null &&
                    this.Ignored.Equals(input.Ignored))
                ) && 
                (
                    this.AccountLocked == input.AccountLocked ||
                    (this.AccountLocked != null &&
                    this.AccountLocked.Equals(input.AccountLocked))
                ) && 
                (
                    this.SuspendedPwReset == input.SuspendedPwReset ||
                    (this.SuspendedPwReset != null &&
                    this.SuspendedPwReset.Equals(input.SuspendedPwReset))
                ) && 
                (
                    this.CreatedLast24Hours == input.CreatedLast24Hours ||
                    (this.CreatedLast24Hours != null &&
                    this.CreatedLast24Hours.Equals(input.CreatedLast24Hours))
                ) && 
                (
                    this.CreatedLast7Days == input.CreatedLast7Days ||
                    (this.CreatedLast7Days != null &&
                    this.CreatedLast7Days.Equals(input.CreatedLast7Days))
                ) && 
                (
                    this.CreatedLast30Days == input.CreatedLast30Days ||
                    (this.CreatedLast30Days != null &&
                    this.CreatedLast30Days.Equals(input.CreatedLast30Days))
                ) && 
                (
                    this.ActiveLast24Hours == input.ActiveLast24Hours ||
                    (this.ActiveLast24Hours != null &&
                    this.ActiveLast24Hours.Equals(input.ActiveLast24Hours))
                ) && 
                (
                    this.ActiveLast7Days == input.ActiveLast7Days ||
                    (this.ActiveLast7Days != null &&
                    this.ActiveLast7Days.Equals(input.ActiveLast7Days))
                ) && 
                (
                    this.ActiveLast30Days == input.ActiveLast30Days ||
                    (this.ActiveLast30Days != null &&
                    this.ActiveLast30Days.Equals(input.ActiveLast30Days))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.CollectedAt != null)
                {
                    hashCode = (hashCode * 59) + this.CollectedAt.GetHashCode();
                }
                if (this.PersonalUsers != null)
                {
                    hashCode = (hashCode * 59) + this.PersonalUsers.GetHashCode();
                }
                if (this.ServiceUsers != null)
                {
                    hashCode = (hashCode * 59) + this.ServiceUsers.GetHashCode();
                }
                if (this.NeverLoggedIn != null)
                {
                    hashCode = (hashCode * 59) + this.NeverLoggedIn.GetHashCode();
                }
                if (this.Ignored != null)
                {
                    hashCode = (hashCode * 59) + this.Ignored.GetHashCode();
                }
                if (this.AccountLocked != null)
                {
                    hashCode = (hashCode * 59) + this.AccountLocked.GetHashCode();
                }
                if (this.SuspendedPwReset != null)
                {
                    hashCode = (hashCode * 59) + this.SuspendedPwReset.GetHashCode();
                }
                if (this.CreatedLast24Hours != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedLast24Hours.GetHashCode();
                }
                if (this.CreatedLast7Days != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedLast7Days.GetHashCode();
                }
                if (this.CreatedLast30Days != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedLast30Days.GetHashCode();
                }
                if (this.ActiveLast24Hours != null)
                {
                    hashCode = (hashCode * 59) + this.ActiveLast24Hours.GetHashCode();
                }
                if (this.ActiveLast7Days != null)
                {
                    hashCode = (hashCode * 59) + this.ActiveLast7Days.GetHashCode();
                }
                if (this.ActiveLast30Days != null)
                {
                    hashCode = (hashCode * 59) + this.ActiveLast30Days.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            yield break;
        }
    }
}
