/*
 * FINBOURNE Insights API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Insights.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Insights.Sdk.Model
{
    /// <summary>
    /// A single filter applied to a queryable log field. Exactly one comparator (Finbourne.Insights.WebApi.Dtos.Querying.InsightsFilter.Text, Finbourne.Insights.WebApi.Dtos.Querying.InsightsFilter.Numeric, Finbourne.Insights.WebApi.Dtos.Querying.InsightsFilter.Date or Finbourne.Insights.WebApi.Dtos.Querying.InsightsFilter.Boolean) must be populated, and its type must match the data type of the field named by Finbourne.Insights.WebApi.Dtos.Querying.InsightsFilter.Field. The available comparator and operation for a field can be discovered via the queryable-fields metadata endpoint.
    /// </summary>
    [DataContract(Name = "InsightsFilter")]
    public partial class InsightsFilter : IEquatable<InsightsFilter>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InsightsFilter" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InsightsFilter() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InsightsFilter" /> class.
        /// </summary>
        /// <param name="field">The name of the field to filter on (case-insensitive). Must be a filterable field of the queried log type. (required).</param>
        /// <param name="text">text.</param>
        /// <param name="numeric">numeric.</param>
        /// <param name="date">date.</param>
        /// <param name="boolean">boolean.</param>
        public InsightsFilter(string field = default(string), TextComparator text = default(TextComparator), NumericComparator numeric = default(NumericComparator), DateComparator date = default(DateComparator), BooleanComparator boolean = default(BooleanComparator))
        {
            // to ensure "field" is required (not null)
            if (field == null)
            {
                throw new ArgumentNullException("field is a required property for InsightsFilter and cannot be null");
            }
            this.Field = field;
            this.Text = text;
            this.Numeric = numeric;
            this.Date = date;
            this.Boolean = boolean;
        }

        /// <summary>
        /// The name of the field to filter on (case-insensitive). Must be a filterable field of the queried log type.
        /// </summary>
        /// <value>The name of the field to filter on (case-insensitive). Must be a filterable field of the queried log type.</value>
        [DataMember(Name = "field", IsRequired = true, EmitDefaultValue = true)]
        public string Field { get; set; }

        /// <summary>
        /// Gets or Sets Text
        /// </summary>
        [DataMember(Name = "text", EmitDefaultValue = false)]
        public TextComparator Text { get; set; }

        /// <summary>
        /// Gets or Sets Numeric
        /// </summary>
        [DataMember(Name = "numeric", EmitDefaultValue = false)]
        public NumericComparator Numeric { get; set; }

        /// <summary>
        /// Gets or Sets Date
        /// </summary>
        [DataMember(Name = "date", EmitDefaultValue = false)]
        public DateComparator Date { get; set; }

        /// <summary>
        /// Gets or Sets Boolean
        /// </summary>
        [DataMember(Name = "boolean", EmitDefaultValue = false)]
        public BooleanComparator Boolean { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InsightsFilter {\n");
            sb.Append("  Field: ").Append(Field).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Numeric: ").Append(Numeric).Append("\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  Boolean: ").Append(Boolean).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InsightsFilter);
        }

        /// <summary>
        /// Returns true if InsightsFilter instances are equal
        /// </summary>
        /// <param name="input">Instance of InsightsFilter to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InsightsFilter input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Field == input.Field ||
                    (this.Field != null &&
                    this.Field.Equals(input.Field))
                ) && 
                (
                    this.Text == input.Text ||
                    (this.Text != null &&
                    this.Text.Equals(input.Text))
                ) && 
                (
                    this.Numeric == input.Numeric ||
                    (this.Numeric != null &&
                    this.Numeric.Equals(input.Numeric))
                ) && 
                (
                    this.Date == input.Date ||
                    (this.Date != null &&
                    this.Date.Equals(input.Date))
                ) && 
                (
                    this.Boolean == input.Boolean ||
                    (this.Boolean != null &&
                    this.Boolean.Equals(input.Boolean))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Field != null)
                {
                    hashCode = (hashCode * 59) + this.Field.GetHashCode();
                }
                if (this.Text != null)
                {
                    hashCode = (hashCode * 59) + this.Text.GetHashCode();
                }
                if (this.Numeric != null)
                {
                    hashCode = (hashCode * 59) + this.Numeric.GetHashCode();
                }
                if (this.Date != null)
                {
                    hashCode = (hashCode * 59) + this.Date.GetHashCode();
                }
                if (this.Boolean != null)
                {
                    hashCode = (hashCode * 59) + this.Boolean.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Field (string) maxLength
            if (this.Field != null && this.Field.Length > 64)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Field, length must be less than 64.", new [] { "Field" });
            }

            // Field (string) minLength
            if (this.Field != null && this.Field.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Field, length must be greater than 1.", new [] { "Field" });
            }

            // Field (string) pattern
            Regex regexField = new Regex(@"^[a-zA-Z0-9\-_]+$", RegexOptions.CultureInvariant);
            if (false == regexField.Match(this.Field).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Field, must match a pattern of " + regexField, new [] { "Field" });
            }

            yield break;
        }
    }
}
