/*
 * FINBOURNE Insights API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Insights.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Insights.Sdk.Model
{
    /// <summary>
    /// The aggregated platform metrics for a domain: one nullable, strongly-typed property per data set.
    /// </summary>
    [DataContract(Name = "MetricsResponse")]
    public partial class MetricsResponse : IEquatable<MetricsResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MetricsResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsResponse" /> class.
        /// </summary>
        /// <param name="asAt">When this response was assembled, in UTC. Every data set in the response was resolved against this instant. (required).</param>
        /// <param name="domain">The domain the metrics are for, resolved from the authenticated request rather than from any parameter. (required).</param>
        /// <param name="requestsPerMinute">requestsPerMinute.</param>
        /// <param name="serviceEndpointDurations24h">serviceEndpointDurations24h.</param>
        /// <param name="serviceRequests24h">serviceRequests24h.</param>
        /// <param name="identityMetrics">identityMetrics.</param>
        /// <param name="notIncluded">The data sets the caller excluded via the &#x60;include&#x60; parameter, and which were therefore never queried. Each value is one of the Finbourne.Insights.WebApi.Dtos.Metrics.MetricDataSet values. (required).</param>
        /// <param name="failed">The data sets that were requested but could not be returned, each with a caller-safe reason. (required).</param>
        /// <param name="links">links.</param>
        public MetricsResponse(DateTimeOffset asAt = default(DateTimeOffset), string domain = default(string), RequestsPerMinuteDataSet requestsPerMinute = default(RequestsPerMinuteDataSet), ServiceEndpointDurations24hDataSet serviceEndpointDurations24h = default(ServiceEndpointDurations24hDataSet), ServiceRequests24hDataSet serviceRequests24h = default(ServiceRequests24hDataSet), IdentityMetricsDataSet identityMetrics = default(IdentityMetricsDataSet), List<string> notIncluded = default(List<string>), List<MetricDataSetFailure> failed = default(List<MetricDataSetFailure>), List<Link> links = default(List<Link>))
        {
            this.AsAt = asAt;
            // to ensure "domain" is required (not null)
            if (domain == null)
            {
                throw new ArgumentNullException("domain is a required property for MetricsResponse and cannot be null");
            }
            this.Domain = domain;
            // to ensure "notIncluded" is required (not null)
            if (notIncluded == null)
            {
                throw new ArgumentNullException("notIncluded is a required property for MetricsResponse and cannot be null");
            }
            this.NotIncluded = notIncluded;
            // to ensure "failed" is required (not null)
            if (failed == null)
            {
                throw new ArgumentNullException("failed is a required property for MetricsResponse and cannot be null");
            }
            this.Failed = failed;
            this.RequestsPerMinute = requestsPerMinute;
            this.ServiceEndpointDurations24h = serviceEndpointDurations24h;
            this.ServiceRequests24h = serviceRequests24h;
            this.IdentityMetrics = identityMetrics;
            this.Links = links;
        }

        /// <summary>
        /// When this response was assembled, in UTC. Every data set in the response was resolved against this instant.
        /// </summary>
        /// <value>When this response was assembled, in UTC. Every data set in the response was resolved against this instant.</value>
        [DataMember(Name = "asAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset AsAt { get; set; }

        /// <summary>
        /// The domain the metrics are for, resolved from the authenticated request rather than from any parameter.
        /// </summary>
        /// <value>The domain the metrics are for, resolved from the authenticated request rather than from any parameter.</value>
        [DataMember(Name = "domain", IsRequired = true, EmitDefaultValue = true)]
        public string Domain { get; set; }

        /// <summary>
        /// Gets or Sets RequestsPerMinute
        /// </summary>
        [DataMember(Name = "requestsPerMinute", EmitDefaultValue = false)]
        public RequestsPerMinuteDataSet RequestsPerMinute { get; set; }

        /// <summary>
        /// Gets or Sets ServiceEndpointDurations24h
        /// </summary>
        [DataMember(Name = "serviceEndpointDurations24h", EmitDefaultValue = false)]
        public ServiceEndpointDurations24hDataSet ServiceEndpointDurations24h { get; set; }

        /// <summary>
        /// Gets or Sets ServiceRequests24h
        /// </summary>
        [DataMember(Name = "serviceRequests24h", EmitDefaultValue = false)]
        public ServiceRequests24hDataSet ServiceRequests24h { get; set; }

        /// <summary>
        /// Gets or Sets IdentityMetrics
        /// </summary>
        [DataMember(Name = "identityMetrics", EmitDefaultValue = false)]
        public IdentityMetricsDataSet IdentityMetrics { get; set; }

        /// <summary>
        /// The data sets the caller excluded via the &#x60;include&#x60; parameter, and which were therefore never queried. Each value is one of the Finbourne.Insights.WebApi.Dtos.Metrics.MetricDataSet values.
        /// </summary>
        /// <value>The data sets the caller excluded via the &#x60;include&#x60; parameter, and which were therefore never queried. Each value is one of the Finbourne.Insights.WebApi.Dtos.Metrics.MetricDataSet values.</value>
        [DataMember(Name = "notIncluded", IsRequired = true, EmitDefaultValue = true)]
        public List<string> NotIncluded { get; set; }

        /// <summary>
        /// The data sets that were requested but could not be returned, each with a caller-safe reason.
        /// </summary>
        /// <value>The data sets that were requested but could not be returned, each with a caller-safe reason.</value>
        [DataMember(Name = "failed", IsRequired = true, EmitDefaultValue = true)]
        public List<MetricDataSetFailure> Failed { get; set; }

        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name = "links", EmitDefaultValue = true)]
        public List<Link> Links { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MetricsResponse {\n");
            sb.Append("  AsAt: ").Append(AsAt).Append("\n");
            sb.Append("  Domain: ").Append(Domain).Append("\n");
            sb.Append("  RequestsPerMinute: ").Append(RequestsPerMinute).Append("\n");
            sb.Append("  ServiceEndpointDurations24h: ").Append(ServiceEndpointDurations24h).Append("\n");
            sb.Append("  ServiceRequests24h: ").Append(ServiceRequests24h).Append("\n");
            sb.Append("  IdentityMetrics: ").Append(IdentityMetrics).Append("\n");
            sb.Append("  NotIncluded: ").Append(NotIncluded).Append("\n");
            sb.Append("  Failed: ").Append(Failed).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MetricsResponse);
        }

        /// <summary>
        /// Returns true if MetricsResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of MetricsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MetricsResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.AsAt == input.AsAt ||
                    (this.AsAt != null &&
                    this.AsAt.Equals(input.AsAt))
                ) && 
                (
                    this.Domain == input.Domain ||
                    (this.Domain != null &&
                    this.Domain.Equals(input.Domain))
                ) && 
                (
                    this.RequestsPerMinute == input.RequestsPerMinute ||
                    (this.RequestsPerMinute != null &&
                    this.RequestsPerMinute.Equals(input.RequestsPerMinute))
                ) && 
                (
                    this.ServiceEndpointDurations24h == input.ServiceEndpointDurations24h ||
                    (this.ServiceEndpointDurations24h != null &&
                    this.ServiceEndpointDurations24h.Equals(input.ServiceEndpointDurations24h))
                ) && 
                (
                    this.ServiceRequests24h == input.ServiceRequests24h ||
                    (this.ServiceRequests24h != null &&
                    this.ServiceRequests24h.Equals(input.ServiceRequests24h))
                ) && 
                (
                    this.IdentityMetrics == input.IdentityMetrics ||
                    (this.IdentityMetrics != null &&
                    this.IdentityMetrics.Equals(input.IdentityMetrics))
                ) && 
                (
                    this.NotIncluded == input.NotIncluded ||
                    this.NotIncluded != null &&
                    input.NotIncluded != null &&
                    this.NotIncluded.SequenceEqual(input.NotIncluded)
                ) && 
                (
                    this.Failed == input.Failed ||
                    this.Failed != null &&
                    input.Failed != null &&
                    this.Failed.SequenceEqual(input.Failed)
                ) && 
                (
                    this.Links == input.Links ||
                    this.Links != null &&
                    input.Links != null &&
                    this.Links.SequenceEqual(input.Links)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AsAt != null)
                {
                    hashCode = (hashCode * 59) + this.AsAt.GetHashCode();
                }
                if (this.Domain != null)
                {
                    hashCode = (hashCode * 59) + this.Domain.GetHashCode();
                }
                if (this.RequestsPerMinute != null)
                {
                    hashCode = (hashCode * 59) + this.RequestsPerMinute.GetHashCode();
                }
                if (this.ServiceEndpointDurations24h != null)
                {
                    hashCode = (hashCode * 59) + this.ServiceEndpointDurations24h.GetHashCode();
                }
                if (this.ServiceRequests24h != null)
                {
                    hashCode = (hashCode * 59) + this.ServiceRequests24h.GetHashCode();
                }
                if (this.IdentityMetrics != null)
                {
                    hashCode = (hashCode * 59) + this.IdentityMetrics.GetHashCode();
                }
                if (this.NotIncluded != null)
                {
                    hashCode = (hashCode * 59) + this.NotIncluded.GetHashCode();
                }
                if (this.Failed != null)
                {
                    hashCode = (hashCode * 59) + this.Failed.GetHashCode();
                }
                if (this.Links != null)
                {
                    hashCode = (hashCode * 59) + this.Links.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Domain (string) minLength
            if (this.Domain != null && this.Domain.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Domain, length must be greater than 1.", new [] { "Domain" });
            }

            yield break;
        }
    }
}
