/*
 * FINBOURNE Insights API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Insights.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Insights.Sdk.Model
{
    /// <summary>
    /// The queryable fields of a single log type, returned by the queryable-fields metadata endpoint.
    /// </summary>
    [DataContract(Name = "QueryableLogType")]
    public partial class QueryableLogType : IEquatable<QueryableLogType>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryableLogType" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected QueryableLogType() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryableLogType" /> class.
        /// </summary>
        /// <param name="logType">The log type, e.g. Requests, Vendor, Access, Trace or TraceEvent. (required).</param>
        /// <param name="fields">The fields of this log type that can be selected and/or filtered. (required).</param>
        public QueryableLogType(string logType = default(string), List<QueryableLogField> fields = default(List<QueryableLogField>))
        {
            // to ensure "logType" is required (not null)
            if (logType == null)
            {
                throw new ArgumentNullException("logType is a required property for QueryableLogType and cannot be null");
            }
            this.LogType = logType;
            // to ensure "fields" is required (not null)
            if (fields == null)
            {
                throw new ArgumentNullException("fields is a required property for QueryableLogType and cannot be null");
            }
            this.Fields = fields;
        }

        /// <summary>
        /// The log type, e.g. Requests, Vendor, Access, Trace or TraceEvent.
        /// </summary>
        /// <value>The log type, e.g. Requests, Vendor, Access, Trace or TraceEvent.</value>
        [DataMember(Name = "logType", IsRequired = true, EmitDefaultValue = true)]
        public string LogType { get; set; }

        /// <summary>
        /// The fields of this log type that can be selected and/or filtered.
        /// </summary>
        /// <value>The fields of this log type that can be selected and/or filtered.</value>
        [DataMember(Name = "fields", IsRequired = true, EmitDefaultValue = true)]
        public List<QueryableLogField> Fields { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QueryableLogType {\n");
            sb.Append("  LogType: ").Append(LogType).Append("\n");
            sb.Append("  Fields: ").Append(Fields).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as QueryableLogType);
        }

        /// <summary>
        /// Returns true if QueryableLogType instances are equal
        /// </summary>
        /// <param name="input">Instance of QueryableLogType to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(QueryableLogType input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.LogType == input.LogType ||
                    (this.LogType != null &&
                    this.LogType.Equals(input.LogType))
                ) && 
                (
                    this.Fields == input.Fields ||
                    this.Fields != null &&
                    input.Fields != null &&
                    this.Fields.SequenceEqual(input.Fields)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LogType != null)
                {
                    hashCode = (hashCode * 59) + this.LogType.GetHashCode();
                }
                if (this.Fields != null)
                {
                    hashCode = (hashCode * 59) + this.Fields.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // LogType (string) minLength
            if (this.LogType != null && this.LogType.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for LogType, length must be greater than 1.", new [] { "LogType" });
            }

            yield break;
        }
    }
}
