/*
 * FINBOURNE Insights API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Insights.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Insights.Sdk.Model
{
    /// <summary>
    /// Body of the QueryRequestLogs endpoint. A query is bounded by a time range (Finbourne.Insights.WebApi.Dtos.QueryRequestLogsRequest.StartAt/Finbourne.Insights.WebApi.Dtos.QueryRequestLogsRequest.EndAt) and refined by an optional set of Finbourne.Insights.WebApi.Dtos.QueryRequestLogsRequest.Filters that are combined with logical AND. The discoverable set of filterable fields, their data types and the operations available for each is returned by the queryable-fields metadata endpoint.
    /// </summary>
    [DataContract(Name = "QueryRequestLogsRequest")]
    public partial class QueryRequestLogsRequest : IEquatable<QueryRequestLogsRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryRequestLogsRequest" /> class.
        /// </summary>
        /// <param name="startAt">The inclusive start of the time range to query. Required unless Finbourne.Insights.WebApi.Dtos.QueryRequestLogsRequest.Page is supplied. Used to bound the underlying partition scan, so a tighter range is cheaper and faster..</param>
        /// <param name="endAt">The end of the time range to query. Required unless Finbourne.Insights.WebApi.Dtos.QueryRequestLogsRequest.Page or Finbourne.Insights.WebApi.Dtos.QueryRequestLogsRequest.TimeRange is supplied..</param>
        /// <param name="timeRange">timeRange.</param>
        /// <param name="filters">Optional filters to apply, combined with logical AND. Each filter targets a filterable field and supplies exactly one comparator matching that field&#39;s data type..</param>
        /// <param name="sortBy">Order the results by these fields. Use the &#39;-&#39; sign to denote descending order e.g. -MyFieldName. Multiple fields can be denoted by a comma e.g. -MyFieldName,AnotherFieldName,-AFurtherFieldName..</param>
        /// <param name="maxResults">The maximum total number of records to capture in the result set; applied as the Luminesce query limit and so bounding the work the query performs. The minimum value is 1 and the maximum is 10000; defaults to 500 when not supplied. The per-page limit then controls how many of these captured records are returned per page..</param>
        /// <param name="limit">When paginating, only return this number of records per page. The minimum value is 0 (return all captured records in a single page) and the maximum is 10000..</param>
        /// <param name="page">Encoded page string returned from a previous search result that will retrieve the next page of data. When this field is supplied, the query-defining fields should not be supplied..</param>
        /// <param name="fields">Optional list of additional field names to include in the response. The fields Timestamp, Id, Application and Operation are always returned. Values are matched case-insensitively against the queryable fields of the request logs..</param>
        public QueryRequestLogsRequest(DateTimeOffset? startAt = default(DateTimeOffset?), DateTimeOffset? endAt = default(DateTimeOffset?), TimeRange timeRange = default(TimeRange), List<InsightsFilter> filters = default(List<InsightsFilter>), string sortBy = default(string), int? maxResults = default(int?), int limit = default(int), string page = default(string), List<string> fields = default(List<string>))
        {
            this.StartAt = startAt;
            this.EndAt = endAt;
            this.TimeRange = timeRange;
            this.Filters = filters;
            this.SortBy = sortBy;
            this.MaxResults = maxResults;
            this.Limit = limit;
            this.Page = page;
            this.Fields = fields;
        }

        /// <summary>
        /// The inclusive start of the time range to query. Required unless Finbourne.Insights.WebApi.Dtos.QueryRequestLogsRequest.Page is supplied. Used to bound the underlying partition scan, so a tighter range is cheaper and faster.
        /// </summary>
        /// <value>The inclusive start of the time range to query. Required unless Finbourne.Insights.WebApi.Dtos.QueryRequestLogsRequest.Page is supplied. Used to bound the underlying partition scan, so a tighter range is cheaper and faster.</value>
        [DataMember(Name = "startAt", EmitDefaultValue = true)]
        public DateTimeOffset? StartAt { get; set; }

        /// <summary>
        /// The end of the time range to query. Required unless Finbourne.Insights.WebApi.Dtos.QueryRequestLogsRequest.Page or Finbourne.Insights.WebApi.Dtos.QueryRequestLogsRequest.TimeRange is supplied.
        /// </summary>
        /// <value>The end of the time range to query. Required unless Finbourne.Insights.WebApi.Dtos.QueryRequestLogsRequest.Page or Finbourne.Insights.WebApi.Dtos.QueryRequestLogsRequest.TimeRange is supplied.</value>
        [DataMember(Name = "endAt", EmitDefaultValue = true)]
        public DateTimeOffset? EndAt { get; set; }

        /// <summary>
        /// Gets or Sets TimeRange
        /// </summary>
        [DataMember(Name = "timeRange", EmitDefaultValue = false)]
        public TimeRange TimeRange { get; set; }

        /// <summary>
        /// Optional filters to apply, combined with logical AND. Each filter targets a filterable field and supplies exactly one comparator matching that field&#39;s data type.
        /// </summary>
        /// <value>Optional filters to apply, combined with logical AND. Each filter targets a filterable field and supplies exactly one comparator matching that field&#39;s data type.</value>
        [DataMember(Name = "filters", EmitDefaultValue = true)]
        public List<InsightsFilter> Filters { get; set; }

        /// <summary>
        /// Order the results by these fields. Use the &#39;-&#39; sign to denote descending order e.g. -MyFieldName. Multiple fields can be denoted by a comma e.g. -MyFieldName,AnotherFieldName,-AFurtherFieldName.
        /// </summary>
        /// <value>Order the results by these fields. Use the &#39;-&#39; sign to denote descending order e.g. -MyFieldName. Multiple fields can be denoted by a comma e.g. -MyFieldName,AnotherFieldName,-AFurtherFieldName.</value>
        [DataMember(Name = "sortBy", EmitDefaultValue = true)]
        public string SortBy { get; set; }

        /// <summary>
        /// The maximum total number of records to capture in the result set; applied as the Luminesce query limit and so bounding the work the query performs. The minimum value is 1 and the maximum is 10000; defaults to 500 when not supplied. The per-page limit then controls how many of these captured records are returned per page.
        /// </summary>
        /// <value>The maximum total number of records to capture in the result set; applied as the Luminesce query limit and so bounding the work the query performs. The minimum value is 1 and the maximum is 10000; defaults to 500 when not supplied. The per-page limit then controls how many of these captured records are returned per page.</value>
        [DataMember(Name = "maxResults", EmitDefaultValue = true)]
        public int? MaxResults { get; set; }

        /// <summary>
        /// When paginating, only return this number of records per page. The minimum value is 0 (return all captured records in a single page) and the maximum is 10000.
        /// </summary>
        /// <value>When paginating, only return this number of records per page. The minimum value is 0 (return all captured records in a single page) and the maximum is 10000.</value>
        [DataMember(Name = "limit", EmitDefaultValue = true)]
        public int Limit { get; set; }

        /// <summary>
        /// Encoded page string returned from a previous search result that will retrieve the next page of data. When this field is supplied, the query-defining fields should not be supplied.
        /// </summary>
        /// <value>Encoded page string returned from a previous search result that will retrieve the next page of data. When this field is supplied, the query-defining fields should not be supplied.</value>
        [DataMember(Name = "page", EmitDefaultValue = true)]
        public string Page { get; set; }

        /// <summary>
        /// Optional list of additional field names to include in the response. The fields Timestamp, Id, Application and Operation are always returned. Values are matched case-insensitively against the queryable fields of the request logs.
        /// </summary>
        /// <value>Optional list of additional field names to include in the response. The fields Timestamp, Id, Application and Operation are always returned. Values are matched case-insensitively against the queryable fields of the request logs.</value>
        [DataMember(Name = "fields", EmitDefaultValue = true)]
        public List<string> Fields { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QueryRequestLogsRequest {\n");
            sb.Append("  StartAt: ").Append(StartAt).Append("\n");
            sb.Append("  EndAt: ").Append(EndAt).Append("\n");
            sb.Append("  TimeRange: ").Append(TimeRange).Append("\n");
            sb.Append("  Filters: ").Append(Filters).Append("\n");
            sb.Append("  SortBy: ").Append(SortBy).Append("\n");
            sb.Append("  MaxResults: ").Append(MaxResults).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  Page: ").Append(Page).Append("\n");
            sb.Append("  Fields: ").Append(Fields).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as QueryRequestLogsRequest);
        }

        /// <summary>
        /// Returns true if QueryRequestLogsRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of QueryRequestLogsRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(QueryRequestLogsRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.StartAt == input.StartAt ||
                    (this.StartAt != null &&
                    this.StartAt.Equals(input.StartAt))
                ) && 
                (
                    this.EndAt == input.EndAt ||
                    (this.EndAt != null &&
                    this.EndAt.Equals(input.EndAt))
                ) && 
                (
                    this.TimeRange == input.TimeRange ||
                    (this.TimeRange != null &&
                    this.TimeRange.Equals(input.TimeRange))
                ) && 
                (
                    this.Filters == input.Filters ||
                    this.Filters != null &&
                    input.Filters != null &&
                    this.Filters.SequenceEqual(input.Filters)
                ) && 
                (
                    this.SortBy == input.SortBy ||
                    (this.SortBy != null &&
                    this.SortBy.Equals(input.SortBy))
                ) && 
                (
                    this.MaxResults == input.MaxResults ||
                    (this.MaxResults != null &&
                    this.MaxResults.Equals(input.MaxResults))
                ) && 
                (
                    this.Limit == input.Limit ||
                    this.Limit.Equals(input.Limit)
                ) && 
                (
                    this.Page == input.Page ||
                    (this.Page != null &&
                    this.Page.Equals(input.Page))
                ) && 
                (
                    this.Fields == input.Fields ||
                    this.Fields != null &&
                    input.Fields != null &&
                    this.Fields.SequenceEqual(input.Fields)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.StartAt != null)
                {
                    hashCode = (hashCode * 59) + this.StartAt.GetHashCode();
                }
                if (this.EndAt != null)
                {
                    hashCode = (hashCode * 59) + this.EndAt.GetHashCode();
                }
                if (this.TimeRange != null)
                {
                    hashCode = (hashCode * 59) + this.TimeRange.GetHashCode();
                }
                if (this.Filters != null)
                {
                    hashCode = (hashCode * 59) + this.Filters.GetHashCode();
                }
                if (this.SortBy != null)
                {
                    hashCode = (hashCode * 59) + this.SortBy.GetHashCode();
                }
                if (this.MaxResults != null)
                {
                    hashCode = (hashCode * 59) + this.MaxResults.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Limit.GetHashCode();
                if (this.Page != null)
                {
                    hashCode = (hashCode * 59) + this.Page.GetHashCode();
                }
                if (this.Fields != null)
                {
                    hashCode = (hashCode * 59) + this.Fields.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // SortBy (string) maxLength
            if (this.SortBy != null && this.SortBy.Length > 16384)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SortBy, length must be less than 16384.", new [] { "SortBy" });
            }

            // SortBy (string) minLength
            if (this.SortBy != null && this.SortBy.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SortBy, length must be greater than 1.", new [] { "SortBy" });
            }

            // SortBy (string) pattern
            Regex regexSortBy = new Regex(@"^[\s\S]*$", RegexOptions.CultureInvariant);
            if (false == regexSortBy.Match(this.SortBy).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SortBy, must match a pattern of " + regexSortBy, new [] { "SortBy" });
            }

            // MaxResults (int?) maximum
            if (this.MaxResults > (int?)10000)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MaxResults, must be a value less than or equal to 10000.", new [] { "MaxResults" });
            }

            // MaxResults (int?) minimum
            if (this.MaxResults < (int?)1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MaxResults, must be a value greater than or equal to 1.", new [] { "MaxResults" });
            }

            // Limit (int) maximum
            if (this.Limit > (int)10000)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Limit, must be a value less than or equal to 10000.", new [] { "Limit" });
            }

            // Limit (int) minimum
            if (this.Limit < (int)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Limit, must be a value greater than or equal to 0.", new [] { "Limit" });
            }

            // Page (string) maxLength
            if (this.Page != null && this.Page.Length > 4500)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Page, length must be less than 4500.", new [] { "Page" });
            }

            // Page (string) minLength
            if (this.Page != null && this.Page.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Page, length must be greater than 1.", new [] { "Page" });
            }

            // Page (string) pattern
            Regex regexPage = new Regex(@"^[a-zA-Z0-9\+/]*={0,3}$", RegexOptions.CultureInvariant);
            if (false == regexPage.Match(this.Page).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Page, must match a pattern of " + regexPage, new [] { "Page" });
            }

            yield break;
        }
    }
}
