/*
 * FINBOURNE Insights API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Insights.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Insights.Sdk.Model
{
    /// <summary>
    /// Describes a field of a log type that can be selected and (where Finbourne.Insights.WebApi.Dtos.Querying.QueryableLogField.Filterable is set) filtered when querying logs, including the comparator operations available for it. Returned by the queryable-fields metadata endpoint so a UI can advertise the correct comparators for each field.
    /// </summary>
    [DataContract(Name = "QueryableLogField")]
    public partial class QueryableLogField : IEquatable<QueryableLogField>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryableLogField" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected QueryableLogField() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryableLogField" /> class.
        /// </summary>
        /// <param name="name">The name of the field, as used when requesting it or filtering on it (case-insensitive). (required).</param>
        /// <param name="dataType">The data type of the field: Text, Numeric, Date or Boolean. (required).</param>
        /// <param name="supportedOperations">The comparator operations available for this field. Empty when the field is not filterable. (required).</param>
        /// <param name="filterable">Whether the field can be used in a filter..</param>
        /// <param name="alwaysReturned">Whether the field is always returned (and therefore need not be requested)..</param>
        public QueryableLogField(string name = default(string), string dataType = default(string), List<string> supportedOperations = default(List<string>), bool filterable = default(bool), bool alwaysReturned = default(bool))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for QueryableLogField and cannot be null");
            }
            this.Name = name;
            // to ensure "dataType" is required (not null)
            if (dataType == null)
            {
                throw new ArgumentNullException("dataType is a required property for QueryableLogField and cannot be null");
            }
            this.DataType = dataType;
            // to ensure "supportedOperations" is required (not null)
            if (supportedOperations == null)
            {
                throw new ArgumentNullException("supportedOperations is a required property for QueryableLogField and cannot be null");
            }
            this.SupportedOperations = supportedOperations;
            this.Filterable = filterable;
            this.AlwaysReturned = alwaysReturned;
        }

        /// <summary>
        /// The name of the field, as used when requesting it or filtering on it (case-insensitive).
        /// </summary>
        /// <value>The name of the field, as used when requesting it or filtering on it (case-insensitive).</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The data type of the field: Text, Numeric, Date or Boolean.
        /// </summary>
        /// <value>The data type of the field: Text, Numeric, Date or Boolean.</value>
        [DataMember(Name = "dataType", IsRequired = true, EmitDefaultValue = true)]
        public string DataType { get; set; }

        /// <summary>
        /// The comparator operations available for this field. Empty when the field is not filterable.
        /// </summary>
        /// <value>The comparator operations available for this field. Empty when the field is not filterable.</value>
        [DataMember(Name = "supportedOperations", IsRequired = true, EmitDefaultValue = true)]
        public List<string> SupportedOperations { get; set; }

        /// <summary>
        /// Whether the field can be used in a filter.
        /// </summary>
        /// <value>Whether the field can be used in a filter.</value>
        [DataMember(Name = "filterable", EmitDefaultValue = true)]
        public bool Filterable { get; set; }

        /// <summary>
        /// Whether the field is always returned (and therefore need not be requested).
        /// </summary>
        /// <value>Whether the field is always returned (and therefore need not be requested).</value>
        [DataMember(Name = "alwaysReturned", EmitDefaultValue = true)]
        public bool AlwaysReturned { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QueryableLogField {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  DataType: ").Append(DataType).Append("\n");
            sb.Append("  SupportedOperations: ").Append(SupportedOperations).Append("\n");
            sb.Append("  Filterable: ").Append(Filterable).Append("\n");
            sb.Append("  AlwaysReturned: ").Append(AlwaysReturned).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as QueryableLogField);
        }

        /// <summary>
        /// Returns true if QueryableLogField instances are equal
        /// </summary>
        /// <param name="input">Instance of QueryableLogField to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(QueryableLogField input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.DataType == input.DataType ||
                    (this.DataType != null &&
                    this.DataType.Equals(input.DataType))
                ) && 
                (
                    this.SupportedOperations == input.SupportedOperations ||
                    this.SupportedOperations != null &&
                    input.SupportedOperations != null &&
                    this.SupportedOperations.SequenceEqual(input.SupportedOperations)
                ) && 
                (
                    this.Filterable == input.Filterable ||
                    this.Filterable.Equals(input.Filterable)
                ) && 
                (
                    this.AlwaysReturned == input.AlwaysReturned ||
                    this.AlwaysReturned.Equals(input.AlwaysReturned)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.DataType != null)
                {
                    hashCode = (hashCode * 59) + this.DataType.GetHashCode();
                }
                if (this.SupportedOperations != null)
                {
                    hashCode = (hashCode * 59) + this.SupportedOperations.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Filterable.GetHashCode();
                hashCode = (hashCode * 59) + this.AlwaysReturned.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            // DataType (string) minLength
            if (this.DataType != null && this.DataType.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DataType, length must be greater than 1.", new [] { "DataType" });
            }

            yield break;
        }
    }
}
