/*
 * FINBOURNE Insights API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Insights.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Insights.Sdk.Model
{
    /// <summary>
    /// One end of a relative time range. Exactly one of the options must be set: Finbourne.Insights.WebApi.Dtos.Querying.RelativeBoundary.Now (the current instant), Finbourne.Insights.WebApi.Dtos.Querying.RelativeBoundary.Midnight (the start of the current day in the range&#39;s time zone), Finbourne.Insights.WebApi.Dtos.Querying.RelativeBoundary.Offset (a duration back from now) or Finbourne.Insights.WebApi.Dtos.Querying.RelativeBoundary.Absolute (an explicit instant).
    /// </summary>
    [DataContract(Name = "RelativeBoundary")]
    public partial class RelativeBoundary : IEquatable<RelativeBoundary>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RelativeBoundary" /> class.
        /// </summary>
        /// <param name="now">When &#x60;true&#x60;, this boundary is the current instant (\&quot;now\&quot;)..</param>
        /// <param name="midnight">When &#x60;true&#x60;, this boundary is the start of the current day (midnight) in the range&#39;s time zone..</param>
        /// <param name="offset">offset.</param>
        /// <param name="absolute">An explicit absolute instant..</param>
        public RelativeBoundary(bool now = default(bool), bool midnight = default(bool), RelativeOffset offset = default(RelativeOffset), DateTimeOffset? absolute = default(DateTimeOffset?))
        {
            this.Now = now;
            this.Midnight = midnight;
            this.Offset = offset;
            this.Absolute = absolute;
        }

        /// <summary>
        /// When &#x60;true&#x60;, this boundary is the current instant (\&quot;now\&quot;).
        /// </summary>
        /// <value>When &#x60;true&#x60;, this boundary is the current instant (\&quot;now\&quot;).</value>
        [DataMember(Name = "now", EmitDefaultValue = true)]
        public bool Now { get; set; }

        /// <summary>
        /// When &#x60;true&#x60;, this boundary is the start of the current day (midnight) in the range&#39;s time zone.
        /// </summary>
        /// <value>When &#x60;true&#x60;, this boundary is the start of the current day (midnight) in the range&#39;s time zone.</value>
        [DataMember(Name = "midnight", EmitDefaultValue = true)]
        public bool Midnight { get; set; }

        /// <summary>
        /// Gets or Sets Offset
        /// </summary>
        [DataMember(Name = "offset", EmitDefaultValue = false)]
        public RelativeOffset Offset { get; set; }

        /// <summary>
        /// An explicit absolute instant.
        /// </summary>
        /// <value>An explicit absolute instant.</value>
        [DataMember(Name = "absolute", EmitDefaultValue = true)]
        public DateTimeOffset? Absolute { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RelativeBoundary {\n");
            sb.Append("  Now: ").Append(Now).Append("\n");
            sb.Append("  Midnight: ").Append(Midnight).Append("\n");
            sb.Append("  Offset: ").Append(Offset).Append("\n");
            sb.Append("  Absolute: ").Append(Absolute).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RelativeBoundary);
        }

        /// <summary>
        /// Returns true if RelativeBoundary instances are equal
        /// </summary>
        /// <param name="input">Instance of RelativeBoundary to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RelativeBoundary input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Now == input.Now ||
                    this.Now.Equals(input.Now)
                ) && 
                (
                    this.Midnight == input.Midnight ||
                    this.Midnight.Equals(input.Midnight)
                ) && 
                (
                    this.Offset == input.Offset ||
                    (this.Offset != null &&
                    this.Offset.Equals(input.Offset))
                ) && 
                (
                    this.Absolute == input.Absolute ||
                    (this.Absolute != null &&
                    this.Absolute.Equals(input.Absolute))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Now.GetHashCode();
                hashCode = (hashCode * 59) + this.Midnight.GetHashCode();
                if (this.Offset != null)
                {
                    hashCode = (hashCode * 59) + this.Offset.GetHashCode();
                }
                if (this.Absolute != null)
                {
                    hashCode = (hashCode * 59) + this.Absolute.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
