/*
 * FINBOURNE Insights API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Insights.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Insights.Sdk.Model
{
    /// <summary>
    /// One minute of request activity for a single service and endpoint.
    /// </summary>
    [DataContract(Name = "RequestsPerMinuteBucket")]
    public partial class RequestsPerMinuteBucket : IEquatable<RequestsPerMinuteBucket>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RequestsPerMinuteBucket" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RequestsPerMinuteBucket() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RequestsPerMinuteBucket" /> class.
        /// </summary>
        /// <param name="minuteBucket">Start of the whole minute this row covers, in UTC. (required).</param>
        /// <param name="service">The name of the service (application) that handled the requests..</param>
        /// <param name="endpoint">The endpoint (API operation) the requests were made to..</param>
        /// <param name="totalRequests">The number of requests in this minute, or null if not reported..</param>
        /// <param name="requests5xx">The number of requests in this minute that returned a 5xx status code, or null if not reported..</param>
        /// <param name="durationSumMs">The sum of the request durations in this minute, in milliseconds, or null if not reported..</param>
        public RequestsPerMinuteBucket(DateTimeOffset minuteBucket = default(DateTimeOffset), string service = default(string), string endpoint = default(string), long? totalRequests = default(long?), long? requests5xx = default(long?), decimal? durationSumMs = default(decimal?))
        {
            this.MinuteBucket = minuteBucket;
            this.Service = service;
            this.Endpoint = endpoint;
            this.TotalRequests = totalRequests;
            this.Requests5xx = requests5xx;
            this.DurationSumMs = durationSumMs;
        }

        /// <summary>
        /// Start of the whole minute this row covers, in UTC.
        /// </summary>
        /// <value>Start of the whole minute this row covers, in UTC.</value>
        [DataMember(Name = "minuteBucket", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset MinuteBucket { get; set; }

        /// <summary>
        /// The name of the service (application) that handled the requests.
        /// </summary>
        /// <value>The name of the service (application) that handled the requests.</value>
        [DataMember(Name = "service", EmitDefaultValue = true)]
        public string Service { get; set; }

        /// <summary>
        /// The endpoint (API operation) the requests were made to.
        /// </summary>
        /// <value>The endpoint (API operation) the requests were made to.</value>
        [DataMember(Name = "endpoint", EmitDefaultValue = true)]
        public string Endpoint { get; set; }

        /// <summary>
        /// The number of requests in this minute, or null if not reported.
        /// </summary>
        /// <value>The number of requests in this minute, or null if not reported.</value>
        [DataMember(Name = "totalRequests", EmitDefaultValue = true)]
        public long? TotalRequests { get; set; }

        /// <summary>
        /// The number of requests in this minute that returned a 5xx status code, or null if not reported.
        /// </summary>
        /// <value>The number of requests in this minute that returned a 5xx status code, or null if not reported.</value>
        [DataMember(Name = "requests5xx", EmitDefaultValue = true)]
        public long? Requests5xx { get; set; }

        /// <summary>
        /// The sum of the request durations in this minute, in milliseconds, or null if not reported.
        /// </summary>
        /// <value>The sum of the request durations in this minute, in milliseconds, or null if not reported.</value>
        [DataMember(Name = "durationSumMs", EmitDefaultValue = true)]
        public decimal? DurationSumMs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RequestsPerMinuteBucket {\n");
            sb.Append("  MinuteBucket: ").Append(MinuteBucket).Append("\n");
            sb.Append("  Service: ").Append(Service).Append("\n");
            sb.Append("  Endpoint: ").Append(Endpoint).Append("\n");
            sb.Append("  TotalRequests: ").Append(TotalRequests).Append("\n");
            sb.Append("  Requests5xx: ").Append(Requests5xx).Append("\n");
            sb.Append("  DurationSumMs: ").Append(DurationSumMs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RequestsPerMinuteBucket);
        }

        /// <summary>
        /// Returns true if RequestsPerMinuteBucket instances are equal
        /// </summary>
        /// <param name="input">Instance of RequestsPerMinuteBucket to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RequestsPerMinuteBucket input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.MinuteBucket == input.MinuteBucket ||
                    (this.MinuteBucket != null &&
                    this.MinuteBucket.Equals(input.MinuteBucket))
                ) && 
                (
                    this.Service == input.Service ||
                    (this.Service != null &&
                    this.Service.Equals(input.Service))
                ) && 
                (
                    this.Endpoint == input.Endpoint ||
                    (this.Endpoint != null &&
                    this.Endpoint.Equals(input.Endpoint))
                ) && 
                (
                    this.TotalRequests == input.TotalRequests ||
                    (this.TotalRequests != null &&
                    this.TotalRequests.Equals(input.TotalRequests))
                ) && 
                (
                    this.Requests5xx == input.Requests5xx ||
                    (this.Requests5xx != null &&
                    this.Requests5xx.Equals(input.Requests5xx))
                ) && 
                (
                    this.DurationSumMs == input.DurationSumMs ||
                    (this.DurationSumMs != null &&
                    this.DurationSumMs.Equals(input.DurationSumMs))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MinuteBucket != null)
                {
                    hashCode = (hashCode * 59) + this.MinuteBucket.GetHashCode();
                }
                if (this.Service != null)
                {
                    hashCode = (hashCode * 59) + this.Service.GetHashCode();
                }
                if (this.Endpoint != null)
                {
                    hashCode = (hashCode * 59) + this.Endpoint.GetHashCode();
                }
                if (this.TotalRequests != null)
                {
                    hashCode = (hashCode * 59) + this.TotalRequests.GetHashCode();
                }
                if (this.Requests5xx != null)
                {
                    hashCode = (hashCode * 59) + this.Requests5xx.GetHashCode();
                }
                if (this.DurationSumMs != null)
                {
                    hashCode = (hashCode * 59) + this.DurationSumMs.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
