/*
 * FINBOURNE Insights API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Insights.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Insights.Sdk.Model
{
    /// <summary>
    /// The request duration distribution for a single service and endpoint over the window.
    /// </summary>
    [DataContract(Name = "ServiceEndpointDuration")]
    public partial class ServiceEndpointDuration : IEquatable<ServiceEndpointDuration>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceEndpointDuration" /> class.
        /// </summary>
        /// <param name="service">The name of the service (application) that handled the requests..</param>
        /// <param name="endpoint">The endpoint (API operation) the requests were made to..</param>
        /// <param name="totalRequests">The number of requests over the window, or null if not reported..</param>
        /// <param name="meanDurationMs">The mean request duration in milliseconds, or null if not reported..</param>
        /// <param name="medianDurationMs">The median (50th percentile) request duration in milliseconds, or null if not reported..</param>
        /// <param name="p95DurationMs">The 95th percentile request duration in milliseconds, or null if not reported..</param>
        public ServiceEndpointDuration(string service = default(string), string endpoint = default(string), long? totalRequests = default(long?), decimal? meanDurationMs = default(decimal?), decimal? medianDurationMs = default(decimal?), decimal? p95DurationMs = default(decimal?))
        {
            this.Service = service;
            this.Endpoint = endpoint;
            this.TotalRequests = totalRequests;
            this.MeanDurationMs = meanDurationMs;
            this.MedianDurationMs = medianDurationMs;
            this.P95DurationMs = p95DurationMs;
        }

        /// <summary>
        /// The name of the service (application) that handled the requests.
        /// </summary>
        /// <value>The name of the service (application) that handled the requests.</value>
        [DataMember(Name = "service", EmitDefaultValue = true)]
        public string Service { get; set; }

        /// <summary>
        /// The endpoint (API operation) the requests were made to.
        /// </summary>
        /// <value>The endpoint (API operation) the requests were made to.</value>
        [DataMember(Name = "endpoint", EmitDefaultValue = true)]
        public string Endpoint { get; set; }

        /// <summary>
        /// The number of requests over the window, or null if not reported.
        /// </summary>
        /// <value>The number of requests over the window, or null if not reported.</value>
        [DataMember(Name = "totalRequests", EmitDefaultValue = true)]
        public long? TotalRequests { get; set; }

        /// <summary>
        /// The mean request duration in milliseconds, or null if not reported.
        /// </summary>
        /// <value>The mean request duration in milliseconds, or null if not reported.</value>
        [DataMember(Name = "meanDurationMs", EmitDefaultValue = true)]
        public decimal? MeanDurationMs { get; set; }

        /// <summary>
        /// The median (50th percentile) request duration in milliseconds, or null if not reported.
        /// </summary>
        /// <value>The median (50th percentile) request duration in milliseconds, or null if not reported.</value>
        [DataMember(Name = "medianDurationMs", EmitDefaultValue = true)]
        public decimal? MedianDurationMs { get; set; }

        /// <summary>
        /// The 95th percentile request duration in milliseconds, or null if not reported.
        /// </summary>
        /// <value>The 95th percentile request duration in milliseconds, or null if not reported.</value>
        [DataMember(Name = "p95DurationMs", EmitDefaultValue = true)]
        public decimal? P95DurationMs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ServiceEndpointDuration {\n");
            sb.Append("  Service: ").Append(Service).Append("\n");
            sb.Append("  Endpoint: ").Append(Endpoint).Append("\n");
            sb.Append("  TotalRequests: ").Append(TotalRequests).Append("\n");
            sb.Append("  MeanDurationMs: ").Append(MeanDurationMs).Append("\n");
            sb.Append("  MedianDurationMs: ").Append(MedianDurationMs).Append("\n");
            sb.Append("  P95DurationMs: ").Append(P95DurationMs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ServiceEndpointDuration);
        }

        /// <summary>
        /// Returns true if ServiceEndpointDuration instances are equal
        /// </summary>
        /// <param name="input">Instance of ServiceEndpointDuration to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ServiceEndpointDuration input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Service == input.Service ||
                    (this.Service != null &&
                    this.Service.Equals(input.Service))
                ) && 
                (
                    this.Endpoint == input.Endpoint ||
                    (this.Endpoint != null &&
                    this.Endpoint.Equals(input.Endpoint))
                ) && 
                (
                    this.TotalRequests == input.TotalRequests ||
                    (this.TotalRequests != null &&
                    this.TotalRequests.Equals(input.TotalRequests))
                ) && 
                (
                    this.MeanDurationMs == input.MeanDurationMs ||
                    (this.MeanDurationMs != null &&
                    this.MeanDurationMs.Equals(input.MeanDurationMs))
                ) && 
                (
                    this.MedianDurationMs == input.MedianDurationMs ||
                    (this.MedianDurationMs != null &&
                    this.MedianDurationMs.Equals(input.MedianDurationMs))
                ) && 
                (
                    this.P95DurationMs == input.P95DurationMs ||
                    (this.P95DurationMs != null &&
                    this.P95DurationMs.Equals(input.P95DurationMs))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Service != null)
                {
                    hashCode = (hashCode * 59) + this.Service.GetHashCode();
                }
                if (this.Endpoint != null)
                {
                    hashCode = (hashCode * 59) + this.Endpoint.GetHashCode();
                }
                if (this.TotalRequests != null)
                {
                    hashCode = (hashCode * 59) + this.TotalRequests.GetHashCode();
                }
                if (this.MeanDurationMs != null)
                {
                    hashCode = (hashCode * 59) + this.MeanDurationMs.GetHashCode();
                }
                if (this.MedianDurationMs != null)
                {
                    hashCode = (hashCode * 59) + this.MedianDurationMs.GetHashCode();
                }
                if (this.P95DurationMs != null)
                {
                    hashCode = (hashCode * 59) + this.P95DurationMs.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
