/*
 * FINBOURNE Insights API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Insights.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Insights.Sdk.Model
{
    /// <summary>
    /// Request duration distribution per service and endpoint over a rolling twenty four hour window.
    /// </summary>
    [DataContract(Name = "ServiceEndpointDurations24hDataSet")]
    public partial class ServiceEndpointDurations24hDataSet : IEquatable<ServiceEndpointDurations24hDataSet>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceEndpointDurations24hDataSet" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ServiceEndpointDurations24hDataSet() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceEndpointDurations24hDataSet" /> class.
        /// </summary>
        /// <param name="name">The name of this data set. Always &#x60;ServiceEndpointDurations24h&#x60;, matching the corresponding Finbourne.Insights.WebApi.Dtos.Metrics.MetricDataSet value and Finbourne.Insights.WebApi.Dtos.Metrics.MetricsResponse property. (required).</param>
        /// <param name="windowStart">Inclusive start of the window the data covers, in UTC, floored to a whole minute. (required).</param>
        /// <param name="windowEnd">End of the window the data covers, in UTC, floored to a whole minute. (required).</param>
        /// <param name="truncated">True when the query reached the row cap, so some services or endpoints are missing. False when the whole result set was returned. (required).</param>
        /// <param name="values">The rows, ordered by service then endpoint. (required).</param>
        public ServiceEndpointDurations24hDataSet(string name = default(string), DateTimeOffset windowStart = default(DateTimeOffset), DateTimeOffset windowEnd = default(DateTimeOffset), bool truncated = default(bool), List<ServiceEndpointDuration> values = default(List<ServiceEndpointDuration>))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for ServiceEndpointDurations24hDataSet and cannot be null");
            }
            this.Name = name;
            this.WindowStart = windowStart;
            this.WindowEnd = windowEnd;
            this.Truncated = truncated;
            // to ensure "values" is required (not null)
            if (values == null)
            {
                throw new ArgumentNullException("values is a required property for ServiceEndpointDurations24hDataSet and cannot be null");
            }
            this.Values = values;
        }

        /// <summary>
        /// The name of this data set. Always &#x60;ServiceEndpointDurations24h&#x60;, matching the corresponding Finbourne.Insights.WebApi.Dtos.Metrics.MetricDataSet value and Finbourne.Insights.WebApi.Dtos.Metrics.MetricsResponse property.
        /// </summary>
        /// <value>The name of this data set. Always &#x60;ServiceEndpointDurations24h&#x60;, matching the corresponding Finbourne.Insights.WebApi.Dtos.Metrics.MetricDataSet value and Finbourne.Insights.WebApi.Dtos.Metrics.MetricsResponse property.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Inclusive start of the window the data covers, in UTC, floored to a whole minute.
        /// </summary>
        /// <value>Inclusive start of the window the data covers, in UTC, floored to a whole minute.</value>
        [DataMember(Name = "windowStart", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset WindowStart { get; set; }

        /// <summary>
        /// End of the window the data covers, in UTC, floored to a whole minute.
        /// </summary>
        /// <value>End of the window the data covers, in UTC, floored to a whole minute.</value>
        [DataMember(Name = "windowEnd", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset WindowEnd { get; set; }

        /// <summary>
        /// True when the query reached the row cap, so some services or endpoints are missing. False when the whole result set was returned.
        /// </summary>
        /// <value>True when the query reached the row cap, so some services or endpoints are missing. False when the whole result set was returned.</value>
        [DataMember(Name = "truncated", IsRequired = true, EmitDefaultValue = true)]
        public bool Truncated { get; set; }

        /// <summary>
        /// The rows, ordered by service then endpoint.
        /// </summary>
        /// <value>The rows, ordered by service then endpoint.</value>
        [DataMember(Name = "values", IsRequired = true, EmitDefaultValue = true)]
        public List<ServiceEndpointDuration> Values { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ServiceEndpointDurations24hDataSet {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  WindowStart: ").Append(WindowStart).Append("\n");
            sb.Append("  WindowEnd: ").Append(WindowEnd).Append("\n");
            sb.Append("  Truncated: ").Append(Truncated).Append("\n");
            sb.Append("  Values: ").Append(Values).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ServiceEndpointDurations24hDataSet);
        }

        /// <summary>
        /// Returns true if ServiceEndpointDurations24hDataSet instances are equal
        /// </summary>
        /// <param name="input">Instance of ServiceEndpointDurations24hDataSet to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ServiceEndpointDurations24hDataSet input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.WindowStart == input.WindowStart ||
                    (this.WindowStart != null &&
                    this.WindowStart.Equals(input.WindowStart))
                ) && 
                (
                    this.WindowEnd == input.WindowEnd ||
                    (this.WindowEnd != null &&
                    this.WindowEnd.Equals(input.WindowEnd))
                ) && 
                (
                    this.Truncated == input.Truncated ||
                    this.Truncated.Equals(input.Truncated)
                ) && 
                (
                    this.Values == input.Values ||
                    this.Values != null &&
                    input.Values != null &&
                    this.Values.SequenceEqual(input.Values)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.WindowStart != null)
                {
                    hashCode = (hashCode * 59) + this.WindowStart.GetHashCode();
                }
                if (this.WindowEnd != null)
                {
                    hashCode = (hashCode * 59) + this.WindowEnd.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Truncated.GetHashCode();
                if (this.Values != null)
                {
                    hashCode = (hashCode * 59) + this.Values.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            yield break;
        }
    }
}
