/*
 * FINBOURNE Insights API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Insights.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Insights.Sdk.Model
{
    /// <summary>
    /// The request volume and server-error rate for a single service over the window.
    /// </summary>
    [DataContract(Name = "ServiceRequests")]
    public partial class ServiceRequests : IEquatable<ServiceRequests>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceRequests" /> class.
        /// </summary>
        /// <param name="service">The name of the service (application) that handled the requests..</param>
        /// <param name="totalRequests">The number of requests over the window, or null if not reported..</param>
        /// <param name="requests5xx">The number of requests over the window that returned a 5xx status code, or null if not reported..</param>
        /// <param name="pct5xx">The percentage of requests that returned a 5xx status code, or null if not reported..</param>
        public ServiceRequests(string service = default(string), long? totalRequests = default(long?), long? requests5xx = default(long?), decimal? pct5xx = default(decimal?))
        {
            this.Service = service;
            this.TotalRequests = totalRequests;
            this.Requests5xx = requests5xx;
            this.Pct5xx = pct5xx;
        }

        /// <summary>
        /// The name of the service (application) that handled the requests.
        /// </summary>
        /// <value>The name of the service (application) that handled the requests.</value>
        [DataMember(Name = "service", EmitDefaultValue = true)]
        public string Service { get; set; }

        /// <summary>
        /// The number of requests over the window, or null if not reported.
        /// </summary>
        /// <value>The number of requests over the window, or null if not reported.</value>
        [DataMember(Name = "totalRequests", EmitDefaultValue = true)]
        public long? TotalRequests { get; set; }

        /// <summary>
        /// The number of requests over the window that returned a 5xx status code, or null if not reported.
        /// </summary>
        /// <value>The number of requests over the window that returned a 5xx status code, or null if not reported.</value>
        [DataMember(Name = "requests5xx", EmitDefaultValue = true)]
        public long? Requests5xx { get; set; }

        /// <summary>
        /// The percentage of requests that returned a 5xx status code, or null if not reported.
        /// </summary>
        /// <value>The percentage of requests that returned a 5xx status code, or null if not reported.</value>
        [DataMember(Name = "pct5xx", EmitDefaultValue = true)]
        public decimal? Pct5xx { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ServiceRequests {\n");
            sb.Append("  Service: ").Append(Service).Append("\n");
            sb.Append("  TotalRequests: ").Append(TotalRequests).Append("\n");
            sb.Append("  Requests5xx: ").Append(Requests5xx).Append("\n");
            sb.Append("  Pct5xx: ").Append(Pct5xx).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ServiceRequests);
        }

        /// <summary>
        /// Returns true if ServiceRequests instances are equal
        /// </summary>
        /// <param name="input">Instance of ServiceRequests to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ServiceRequests input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Service == input.Service ||
                    (this.Service != null &&
                    this.Service.Equals(input.Service))
                ) && 
                (
                    this.TotalRequests == input.TotalRequests ||
                    (this.TotalRequests != null &&
                    this.TotalRequests.Equals(input.TotalRequests))
                ) && 
                (
                    this.Requests5xx == input.Requests5xx ||
                    (this.Requests5xx != null &&
                    this.Requests5xx.Equals(input.Requests5xx))
                ) && 
                (
                    this.Pct5xx == input.Pct5xx ||
                    (this.Pct5xx != null &&
                    this.Pct5xx.Equals(input.Pct5xx))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Service != null)
                {
                    hashCode = (hashCode * 59) + this.Service.GetHashCode();
                }
                if (this.TotalRequests != null)
                {
                    hashCode = (hashCode * 59) + this.TotalRequests.GetHashCode();
                }
                if (this.Requests5xx != null)
                {
                    hashCode = (hashCode * 59) + this.Requests5xx.GetHashCode();
                }
                if (this.Pct5xx != null)
                {
                    hashCode = (hashCode * 59) + this.Pct5xx.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
