/*
 * FINBOURNE Insights API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Insights.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Insights.Sdk.Model
{
    /// <summary>
    /// Represents an edge connecting two nodes within a trace diagram.
    /// </summary>
    [DataContract(Name = "TraceDiagramEdge")]
    public partial class TraceDiagramEdge : IEquatable<TraceDiagramEdge>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TraceDiagramEdge" /> class.
        /// </summary>
        /// <param name="id">Sequential identifier of the edge..</param>
        /// <param name="nodeId">Identifier of the parent node..</param>
        /// <param name="childNodeId">Identifier of the child node..</param>
        /// <param name="label">Label displayed for the edge..</param>
        public TraceDiagramEdge(int id = default(int), string nodeId = default(string), string childNodeId = default(string), string label = default(string))
        {
            this.Id = id;
            this.NodeId = nodeId;
            this.ChildNodeId = childNodeId;
            this.Label = label;
        }

        /// <summary>
        /// Sequential identifier of the edge.
        /// </summary>
        /// <value>Sequential identifier of the edge.</value>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public int Id { get; set; }

        /// <summary>
        /// Identifier of the parent node.
        /// </summary>
        /// <value>Identifier of the parent node.</value>
        [DataMember(Name = "nodeId", EmitDefaultValue = true)]
        public string NodeId { get; set; }

        /// <summary>
        /// Identifier of the child node.
        /// </summary>
        /// <value>Identifier of the child node.</value>
        [DataMember(Name = "childNodeId", EmitDefaultValue = true)]
        public string ChildNodeId { get; set; }

        /// <summary>
        /// Label displayed for the edge.
        /// </summary>
        /// <value>Label displayed for the edge.</value>
        [DataMember(Name = "label", EmitDefaultValue = true)]
        public string Label { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TraceDiagramEdge {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  NodeId: ").Append(NodeId).Append("\n");
            sb.Append("  ChildNodeId: ").Append(ChildNodeId).Append("\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TraceDiagramEdge);
        }

        /// <summary>
        /// Returns true if TraceDiagramEdge instances are equal
        /// </summary>
        /// <param name="input">Instance of TraceDiagramEdge to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TraceDiagramEdge input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    this.Id.Equals(input.Id)
                ) && 
                (
                    this.NodeId == input.NodeId ||
                    (this.NodeId != null &&
                    this.NodeId.Equals(input.NodeId))
                ) && 
                (
                    this.ChildNodeId == input.ChildNodeId ||
                    (this.ChildNodeId != null &&
                    this.ChildNodeId.Equals(input.ChildNodeId))
                ) && 
                (
                    this.Label == input.Label ||
                    (this.Label != null &&
                    this.Label.Equals(input.Label))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Id.GetHashCode();
                if (this.NodeId != null)
                {
                    hashCode = (hashCode * 59) + this.NodeId.GetHashCode();
                }
                if (this.ChildNodeId != null)
                {
                    hashCode = (hashCode * 59) + this.ChildNodeId.GetHashCode();
                }
                if (this.Label != null)
                {
                    hashCode = (hashCode * 59) + this.Label.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
