/*
 * FINBOURNE Insights API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Insights.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Insights.Sdk.Model
{
    /// <summary>
    /// Represents a node within a trace diagram.
    /// </summary>
    [DataContract(Name = "TraceDiagramNode")]
    public partial class TraceDiagramNode : IEquatable<TraceDiagramNode>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TraceDiagramNode" /> class.
        /// </summary>
        /// <param name="id">Unique identifier of the node..</param>
        /// <param name="displayName">Display name of the node..</param>
        /// <param name="level">Depth level of the node within the diagram..</param>
        /// <param name="parent">Identifier of the node&#39;s parent. This is null for the root node..</param>
        /// <param name="type">Type classification of the node..</param>
        /// <param name="agentScope">The scope of the agent..</param>
        /// <param name="agentVersion">The version of the agent..</param>
        public TraceDiagramNode(string id = default(string), string displayName = default(string), int level = default(int), string parent = default(string), string type = default(string), string agentScope = default(string), int agentVersion = default(int))
        {
            this.Id = id;
            this.DisplayName = displayName;
            this.Level = level;
            this.Parent = parent;
            this.Type = type;
            this.AgentScope = agentScope;
            this.AgentVersion = agentVersion;
        }

        /// <summary>
        /// Unique identifier of the node.
        /// </summary>
        /// <value>Unique identifier of the node.</value>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Display name of the node.
        /// </summary>
        /// <value>Display name of the node.</value>
        [DataMember(Name = "displayName", EmitDefaultValue = true)]
        public string DisplayName { get; set; }

        /// <summary>
        /// Depth level of the node within the diagram.
        /// </summary>
        /// <value>Depth level of the node within the diagram.</value>
        [DataMember(Name = "level", EmitDefaultValue = true)]
        public int Level { get; set; }

        /// <summary>
        /// Identifier of the node&#39;s parent. This is null for the root node.
        /// </summary>
        /// <value>Identifier of the node&#39;s parent. This is null for the root node.</value>
        [DataMember(Name = "parent", EmitDefaultValue = true)]
        public string Parent { get; set; }

        /// <summary>
        /// Type classification of the node.
        /// </summary>
        /// <value>Type classification of the node.</value>
        [DataMember(Name = "type", EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// The scope of the agent.
        /// </summary>
        /// <value>The scope of the agent.</value>
        [DataMember(Name = "agentScope", EmitDefaultValue = true)]
        public string AgentScope { get; set; }

        /// <summary>
        /// The version of the agent.
        /// </summary>
        /// <value>The version of the agent.</value>
        [DataMember(Name = "agentVersion", EmitDefaultValue = true)]
        public int AgentVersion { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TraceDiagramNode {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  Level: ").Append(Level).Append("\n");
            sb.Append("  Parent: ").Append(Parent).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  AgentScope: ").Append(AgentScope).Append("\n");
            sb.Append("  AgentVersion: ").Append(AgentVersion).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TraceDiagramNode);
        }

        /// <summary>
        /// Returns true if TraceDiagramNode instances are equal
        /// </summary>
        /// <param name="input">Instance of TraceDiagramNode to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TraceDiagramNode input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.DisplayName == input.DisplayName ||
                    (this.DisplayName != null &&
                    this.DisplayName.Equals(input.DisplayName))
                ) && 
                (
                    this.Level == input.Level ||
                    this.Level.Equals(input.Level)
                ) && 
                (
                    this.Parent == input.Parent ||
                    (this.Parent != null &&
                    this.Parent.Equals(input.Parent))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.AgentScope == input.AgentScope ||
                    (this.AgentScope != null &&
                    this.AgentScope.Equals(input.AgentScope))
                ) && 
                (
                    this.AgentVersion == input.AgentVersion ||
                    this.AgentVersion.Equals(input.AgentVersion)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.DisplayName != null)
                {
                    hashCode = (hashCode * 59) + this.DisplayName.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Level.GetHashCode();
                if (this.Parent != null)
                {
                    hashCode = (hashCode * 59) + this.Parent.GetHashCode();
                }
                if (this.Type != null)
                {
                    hashCode = (hashCode * 59) + this.Type.GetHashCode();
                }
                if (this.AgentScope != null)
                {
                    hashCode = (hashCode * 59) + this.AgentScope.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.AgentVersion.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
