/*
 * FINBOURNE Insights API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Insights.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Insights.Sdk.Model
{
    /// <summary>
    /// Holds information about a trace event.
    /// </summary>
    [DataContract(Name = "TraceEventLog")]
    public partial class TraceEventLog : IEquatable<TraceEventLog>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TraceEventLog" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TraceEventLog() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TraceEventLog" /> class.
        /// </summary>
        /// <param name="traceEventId">The identifier of the trace event. (required).</param>
        /// <param name="traceId">The identifier of the parent trace. (required).</param>
        /// <param name="createdAt">The datetime at which the trace event was created. (required).</param>
        /// <param name="eventType">The type of the trace event. (required).</param>
        /// <param name="content">The content of the trace event. (required).</param>
        /// <param name="sessionId">The session ID of the trace event. (required).</param>
        /// <param name="circuitId">The ID of the circuit in which the trace event occurred. (required).</param>
        /// <param name="circuitVersion">The version of the circuit in which the trace event occurred. (required).</param>
        /// <param name="nodeId">The ID of the circuit&#39;s node at which the trace event occured. (required).</param>
        /// <param name="links">links.</param>
        public TraceEventLog(string traceEventId = default(string), string traceId = default(string), DateTimeOffset createdAt = default(DateTimeOffset), string eventType = default(string), string content = default(string), string sessionId = default(string), string circuitId = default(string), string circuitVersion = default(string), string nodeId = default(string), List<Link> links = default(List<Link>))
        {
            // to ensure "traceEventId" is required (not null)
            if (traceEventId == null)
            {
                throw new ArgumentNullException("traceEventId is a required property for TraceEventLog and cannot be null");
            }
            this.TraceEventId = traceEventId;
            // to ensure "traceId" is required (not null)
            if (traceId == null)
            {
                throw new ArgumentNullException("traceId is a required property for TraceEventLog and cannot be null");
            }
            this.TraceId = traceId;
            this.CreatedAt = createdAt;
            // to ensure "eventType" is required (not null)
            if (eventType == null)
            {
                throw new ArgumentNullException("eventType is a required property for TraceEventLog and cannot be null");
            }
            this.EventType = eventType;
            // to ensure "content" is required (not null)
            if (content == null)
            {
                throw new ArgumentNullException("content is a required property for TraceEventLog and cannot be null");
            }
            this.Content = content;
            // to ensure "sessionId" is required (not null)
            if (sessionId == null)
            {
                throw new ArgumentNullException("sessionId is a required property for TraceEventLog and cannot be null");
            }
            this.SessionId = sessionId;
            // to ensure "circuitId" is required (not null)
            if (circuitId == null)
            {
                throw new ArgumentNullException("circuitId is a required property for TraceEventLog and cannot be null");
            }
            this.CircuitId = circuitId;
            // to ensure "circuitVersion" is required (not null)
            if (circuitVersion == null)
            {
                throw new ArgumentNullException("circuitVersion is a required property for TraceEventLog and cannot be null");
            }
            this.CircuitVersion = circuitVersion;
            // to ensure "nodeId" is required (not null)
            if (nodeId == null)
            {
                throw new ArgumentNullException("nodeId is a required property for TraceEventLog and cannot be null");
            }
            this.NodeId = nodeId;
            this.Links = links;
        }

        /// <summary>
        /// The identifier of the trace event.
        /// </summary>
        /// <value>The identifier of the trace event.</value>
        [DataMember(Name = "traceEventId", IsRequired = true, EmitDefaultValue = true)]
        public string TraceEventId { get; set; }

        /// <summary>
        /// The identifier of the parent trace.
        /// </summary>
        /// <value>The identifier of the parent trace.</value>
        [DataMember(Name = "traceId", IsRequired = true, EmitDefaultValue = true)]
        public string TraceId { get; set; }

        /// <summary>
        /// The datetime at which the trace event was created.
        /// </summary>
        /// <value>The datetime at which the trace event was created.</value>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// The type of the trace event.
        /// </summary>
        /// <value>The type of the trace event.</value>
        [DataMember(Name = "eventType", IsRequired = true, EmitDefaultValue = true)]
        public string EventType { get; set; }

        /// <summary>
        /// The content of the trace event.
        /// </summary>
        /// <value>The content of the trace event.</value>
        [DataMember(Name = "content", IsRequired = true, EmitDefaultValue = true)]
        public string Content { get; set; }

        /// <summary>
        /// The session ID of the trace event.
        /// </summary>
        /// <value>The session ID of the trace event.</value>
        [DataMember(Name = "sessionId", IsRequired = true, EmitDefaultValue = true)]
        public string SessionId { get; set; }

        /// <summary>
        /// The ID of the circuit in which the trace event occurred.
        /// </summary>
        /// <value>The ID of the circuit in which the trace event occurred.</value>
        [DataMember(Name = "circuitId", IsRequired = true, EmitDefaultValue = true)]
        public string CircuitId { get; set; }

        /// <summary>
        /// The version of the circuit in which the trace event occurred.
        /// </summary>
        /// <value>The version of the circuit in which the trace event occurred.</value>
        [DataMember(Name = "circuitVersion", IsRequired = true, EmitDefaultValue = true)]
        public string CircuitVersion { get; set; }

        /// <summary>
        /// The ID of the circuit&#39;s node at which the trace event occured.
        /// </summary>
        /// <value>The ID of the circuit&#39;s node at which the trace event occured.</value>
        [DataMember(Name = "nodeId", IsRequired = true, EmitDefaultValue = true)]
        public string NodeId { get; set; }

        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name = "links", EmitDefaultValue = true)]
        public List<Link> Links { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TraceEventLog {\n");
            sb.Append("  TraceEventId: ").Append(TraceEventId).Append("\n");
            sb.Append("  TraceId: ").Append(TraceId).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  EventType: ").Append(EventType).Append("\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  SessionId: ").Append(SessionId).Append("\n");
            sb.Append("  CircuitId: ").Append(CircuitId).Append("\n");
            sb.Append("  CircuitVersion: ").Append(CircuitVersion).Append("\n");
            sb.Append("  NodeId: ").Append(NodeId).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TraceEventLog);
        }

        /// <summary>
        /// Returns true if TraceEventLog instances are equal
        /// </summary>
        /// <param name="input">Instance of TraceEventLog to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TraceEventLog input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TraceEventId == input.TraceEventId ||
                    (this.TraceEventId != null &&
                    this.TraceEventId.Equals(input.TraceEventId))
                ) && 
                (
                    this.TraceId == input.TraceId ||
                    (this.TraceId != null &&
                    this.TraceId.Equals(input.TraceId))
                ) && 
                (
                    this.CreatedAt == input.CreatedAt ||
                    (this.CreatedAt != null &&
                    this.CreatedAt.Equals(input.CreatedAt))
                ) && 
                (
                    this.EventType == input.EventType ||
                    (this.EventType != null &&
                    this.EventType.Equals(input.EventType))
                ) && 
                (
                    this.Content == input.Content ||
                    (this.Content != null &&
                    this.Content.Equals(input.Content))
                ) && 
                (
                    this.SessionId == input.SessionId ||
                    (this.SessionId != null &&
                    this.SessionId.Equals(input.SessionId))
                ) && 
                (
                    this.CircuitId == input.CircuitId ||
                    (this.CircuitId != null &&
                    this.CircuitId.Equals(input.CircuitId))
                ) && 
                (
                    this.CircuitVersion == input.CircuitVersion ||
                    (this.CircuitVersion != null &&
                    this.CircuitVersion.Equals(input.CircuitVersion))
                ) && 
                (
                    this.NodeId == input.NodeId ||
                    (this.NodeId != null &&
                    this.NodeId.Equals(input.NodeId))
                ) && 
                (
                    this.Links == input.Links ||
                    this.Links != null &&
                    input.Links != null &&
                    this.Links.SequenceEqual(input.Links)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TraceEventId != null)
                {
                    hashCode = (hashCode * 59) + this.TraceEventId.GetHashCode();
                }
                if (this.TraceId != null)
                {
                    hashCode = (hashCode * 59) + this.TraceId.GetHashCode();
                }
                if (this.CreatedAt != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedAt.GetHashCode();
                }
                if (this.EventType != null)
                {
                    hashCode = (hashCode * 59) + this.EventType.GetHashCode();
                }
                if (this.Content != null)
                {
                    hashCode = (hashCode * 59) + this.Content.GetHashCode();
                }
                if (this.SessionId != null)
                {
                    hashCode = (hashCode * 59) + this.SessionId.GetHashCode();
                }
                if (this.CircuitId != null)
                {
                    hashCode = (hashCode * 59) + this.CircuitId.GetHashCode();
                }
                if (this.CircuitVersion != null)
                {
                    hashCode = (hashCode * 59) + this.CircuitVersion.GetHashCode();
                }
                if (this.NodeId != null)
                {
                    hashCode = (hashCode * 59) + this.NodeId.GetHashCode();
                }
                if (this.Links != null)
                {
                    hashCode = (hashCode * 59) + this.Links.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // TraceEventId (string) minLength
            if (this.TraceEventId != null && this.TraceEventId.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for TraceEventId, length must be greater than 1.", new [] { "TraceEventId" });
            }

            // TraceId (string) minLength
            if (this.TraceId != null && this.TraceId.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for TraceId, length must be greater than 1.", new [] { "TraceId" });
            }

            // EventType (string) minLength
            if (this.EventType != null && this.EventType.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for EventType, length must be greater than 1.", new [] { "EventType" });
            }

            // Content (string) minLength
            if (this.Content != null && this.Content.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Content, length must be greater than 1.", new [] { "Content" });
            }

            // SessionId (string) minLength
            if (this.SessionId != null && this.SessionId.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SessionId, length must be greater than 1.", new [] { "SessionId" });
            }

            // CircuitId (string) minLength
            if (this.CircuitId != null && this.CircuitId.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CircuitId, length must be greater than 1.", new [] { "CircuitId" });
            }

            // CircuitVersion (string) minLength
            if (this.CircuitVersion != null && this.CircuitVersion.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CircuitVersion, length must be greater than 1.", new [] { "CircuitVersion" });
            }

            // NodeId (string) minLength
            if (this.NodeId != null && this.NodeId.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for NodeId, length must be greater than 1.", new [] { "NodeId" });
            }

            yield break;
        }
    }
}
