/*
 * FINBOURNE Insights API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Insights.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Insights.Sdk.Model
{
    /// <summary>
    /// Holds information about a trace event.
    /// </summary>
    [DataContract(Name = "TraceEventLog")]
    public partial class TraceEventLog : IEquatable<TraceEventLog>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TraceEventLog" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TraceEventLog() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TraceEventLog" /> class.
        /// </summary>
        /// <param name="traceEventId">The identifier of the trace event. (required).</param>
        /// <param name="traceId">The identifier of the parent trace. (required).</param>
        /// <param name="createdAt">The datetime at which the trace event was created. (required).</param>
        /// <param name="eventType">The type of the trace event. (required).</param>
        /// <param name="origin">Whether the event originated from the AI or the user (required).</param>
        /// <param name="content">The content of the trace event. (required).</param>
        /// <param name="agentScope">The scope of the agent currently being interacted with (required).</param>
        /// <param name="agentCode">The code identifier of the agent currently being interacted with (required).</param>
        /// <param name="agentVersion">The version of the circuit in which the trace event occurred. (required).</param>
        /// <param name="nodeId">The ID of the circuit&#39;s node at which the trace event occured. (required).</param>
        /// <param name="links">links.</param>
        public TraceEventLog(string traceEventId = default(string), string traceId = default(string), DateTimeOffset createdAt = default(DateTimeOffset), string eventType = default(string), string origin = default(string), string content = default(string), string agentScope = default(string), string agentCode = default(string), int agentVersion = default(int), string nodeId = default(string), List<Link> links = default(List<Link>))
        {
            // to ensure "traceEventId" is required (not null)
            if (traceEventId == null)
            {
                throw new ArgumentNullException("traceEventId is a required property for TraceEventLog and cannot be null");
            }
            this.TraceEventId = traceEventId;
            // to ensure "traceId" is required (not null)
            if (traceId == null)
            {
                throw new ArgumentNullException("traceId is a required property for TraceEventLog and cannot be null");
            }
            this.TraceId = traceId;
            this.CreatedAt = createdAt;
            // to ensure "eventType" is required (not null)
            if (eventType == null)
            {
                throw new ArgumentNullException("eventType is a required property for TraceEventLog and cannot be null");
            }
            this.EventType = eventType;
            // to ensure "origin" is required (not null)
            if (origin == null)
            {
                throw new ArgumentNullException("origin is a required property for TraceEventLog and cannot be null");
            }
            this.Origin = origin;
            // to ensure "content" is required (not null)
            if (content == null)
            {
                throw new ArgumentNullException("content is a required property for TraceEventLog and cannot be null");
            }
            this.Content = content;
            // to ensure "agentScope" is required (not null)
            if (agentScope == null)
            {
                throw new ArgumentNullException("agentScope is a required property for TraceEventLog and cannot be null");
            }
            this.AgentScope = agentScope;
            // to ensure "agentCode" is required (not null)
            if (agentCode == null)
            {
                throw new ArgumentNullException("agentCode is a required property for TraceEventLog and cannot be null");
            }
            this.AgentCode = agentCode;
            this.AgentVersion = agentVersion;
            // to ensure "nodeId" is required (not null)
            if (nodeId == null)
            {
                throw new ArgumentNullException("nodeId is a required property for TraceEventLog and cannot be null");
            }
            this.NodeId = nodeId;
            this.Links = links;
        }

        /// <summary>
        /// The identifier of the trace event.
        /// </summary>
        /// <value>The identifier of the trace event.</value>
        [DataMember(Name = "traceEventId", IsRequired = true, EmitDefaultValue = true)]
        public string TraceEventId { get; set; }

        /// <summary>
        /// The identifier of the parent trace.
        /// </summary>
        /// <value>The identifier of the parent trace.</value>
        [DataMember(Name = "traceId", IsRequired = true, EmitDefaultValue = true)]
        public string TraceId { get; set; }

        /// <summary>
        /// The datetime at which the trace event was created.
        /// </summary>
        /// <value>The datetime at which the trace event was created.</value>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// The type of the trace event.
        /// </summary>
        /// <value>The type of the trace event.</value>
        [DataMember(Name = "eventType", IsRequired = true, EmitDefaultValue = true)]
        public string EventType { get; set; }

        /// <summary>
        /// Whether the event originated from the AI or the user
        /// </summary>
        /// <value>Whether the event originated from the AI or the user</value>
        [DataMember(Name = "origin", IsRequired = true, EmitDefaultValue = true)]
        public string Origin { get; set; }

        /// <summary>
        /// The content of the trace event.
        /// </summary>
        /// <value>The content of the trace event.</value>
        [DataMember(Name = "content", IsRequired = true, EmitDefaultValue = true)]
        public string Content { get; set; }

        /// <summary>
        /// The scope of the agent currently being interacted with
        /// </summary>
        /// <value>The scope of the agent currently being interacted with</value>
        [DataMember(Name = "agentScope", IsRequired = true, EmitDefaultValue = true)]
        public string AgentScope { get; set; }

        /// <summary>
        /// The code identifier of the agent currently being interacted with
        /// </summary>
        /// <value>The code identifier of the agent currently being interacted with</value>
        [DataMember(Name = "agentCode", IsRequired = true, EmitDefaultValue = true)]
        public string AgentCode { get; set; }

        /// <summary>
        /// The version of the circuit in which the trace event occurred.
        /// </summary>
        /// <value>The version of the circuit in which the trace event occurred.</value>
        [DataMember(Name = "agentVersion", IsRequired = true, EmitDefaultValue = true)]
        public int AgentVersion { get; set; }

        /// <summary>
        /// The ID of the circuit&#39;s node at which the trace event occured.
        /// </summary>
        /// <value>The ID of the circuit&#39;s node at which the trace event occured.</value>
        [DataMember(Name = "nodeId", IsRequired = true, EmitDefaultValue = true)]
        public string NodeId { get; set; }

        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name = "links", EmitDefaultValue = true)]
        public List<Link> Links { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TraceEventLog {\n");
            sb.Append("  TraceEventId: ").Append(TraceEventId).Append("\n");
            sb.Append("  TraceId: ").Append(TraceId).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  EventType: ").Append(EventType).Append("\n");
            sb.Append("  Origin: ").Append(Origin).Append("\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  AgentScope: ").Append(AgentScope).Append("\n");
            sb.Append("  AgentCode: ").Append(AgentCode).Append("\n");
            sb.Append("  AgentVersion: ").Append(AgentVersion).Append("\n");
            sb.Append("  NodeId: ").Append(NodeId).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TraceEventLog);
        }

        /// <summary>
        /// Returns true if TraceEventLog instances are equal
        /// </summary>
        /// <param name="input">Instance of TraceEventLog to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TraceEventLog input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TraceEventId == input.TraceEventId ||
                    (this.TraceEventId != null &&
                    this.TraceEventId.Equals(input.TraceEventId))
                ) && 
                (
                    this.TraceId == input.TraceId ||
                    (this.TraceId != null &&
                    this.TraceId.Equals(input.TraceId))
                ) && 
                (
                    this.CreatedAt == input.CreatedAt ||
                    (this.CreatedAt != null &&
                    this.CreatedAt.Equals(input.CreatedAt))
                ) && 
                (
                    this.EventType == input.EventType ||
                    (this.EventType != null &&
                    this.EventType.Equals(input.EventType))
                ) && 
                (
                    this.Origin == input.Origin ||
                    (this.Origin != null &&
                    this.Origin.Equals(input.Origin))
                ) && 
                (
                    this.Content == input.Content ||
                    (this.Content != null &&
                    this.Content.Equals(input.Content))
                ) && 
                (
                    this.AgentScope == input.AgentScope ||
                    (this.AgentScope != null &&
                    this.AgentScope.Equals(input.AgentScope))
                ) && 
                (
                    this.AgentCode == input.AgentCode ||
                    (this.AgentCode != null &&
                    this.AgentCode.Equals(input.AgentCode))
                ) && 
                (
                    this.AgentVersion == input.AgentVersion ||
                    this.AgentVersion.Equals(input.AgentVersion)
                ) && 
                (
                    this.NodeId == input.NodeId ||
                    (this.NodeId != null &&
                    this.NodeId.Equals(input.NodeId))
                ) && 
                (
                    this.Links == input.Links ||
                    this.Links != null &&
                    input.Links != null &&
                    this.Links.SequenceEqual(input.Links)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TraceEventId != null)
                {
                    hashCode = (hashCode * 59) + this.TraceEventId.GetHashCode();
                }
                if (this.TraceId != null)
                {
                    hashCode = (hashCode * 59) + this.TraceId.GetHashCode();
                }
                if (this.CreatedAt != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedAt.GetHashCode();
                }
                if (this.EventType != null)
                {
                    hashCode = (hashCode * 59) + this.EventType.GetHashCode();
                }
                if (this.Origin != null)
                {
                    hashCode = (hashCode * 59) + this.Origin.GetHashCode();
                }
                if (this.Content != null)
                {
                    hashCode = (hashCode * 59) + this.Content.GetHashCode();
                }
                if (this.AgentScope != null)
                {
                    hashCode = (hashCode * 59) + this.AgentScope.GetHashCode();
                }
                if (this.AgentCode != null)
                {
                    hashCode = (hashCode * 59) + this.AgentCode.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.AgentVersion.GetHashCode();
                if (this.NodeId != null)
                {
                    hashCode = (hashCode * 59) + this.NodeId.GetHashCode();
                }
                if (this.Links != null)
                {
                    hashCode = (hashCode * 59) + this.Links.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // TraceEventId (string) minLength
            if (this.TraceEventId != null && this.TraceEventId.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for TraceEventId, length must be greater than 1.", new [] { "TraceEventId" });
            }

            // TraceId (string) minLength
            if (this.TraceId != null && this.TraceId.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for TraceId, length must be greater than 1.", new [] { "TraceId" });
            }

            // EventType (string) minLength
            if (this.EventType != null && this.EventType.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for EventType, length must be greater than 1.", new [] { "EventType" });
            }

            // Origin (string) minLength
            if (this.Origin != null && this.Origin.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Origin, length must be greater than 1.", new [] { "Origin" });
            }

            // Content (string) minLength
            if (this.Content != null && this.Content.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Content, length must be greater than 1.", new [] { "Content" });
            }

            // AgentScope (string) minLength
            if (this.AgentScope != null && this.AgentScope.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for AgentScope, length must be greater than 1.", new [] { "AgentScope" });
            }

            // AgentCode (string) minLength
            if (this.AgentCode != null && this.AgentCode.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for AgentCode, length must be greater than 1.", new [] { "AgentCode" });
            }

            // NodeId (string) minLength
            if (this.NodeId != null && this.NodeId.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for NodeId, length must be greater than 1.", new [] { "NodeId" });
            }

            yield break;
        }
    }
}
